### ISSUE TITLE
有可能让gemini输出音频吗

### ISSUE THREAD

**Issue by ShawnFan2** [nishuzumi/gemini-teacher#1]
这样对于改进更加明显

**Comment by nishuzumi** [comment]
完全可以，可以把
```
        setup_msg = {
            "setup": {
                "model": f"models/{model}",
                "generation_config": {
                    "response_modalities": ["TEXT"]
                }
            }
        }
```
改成
```
        setup_msg = {
            "setup": {
                "model": f"models/{model}",
                "generation_config": {
                    "response_modalities": ["AUDIO"]
                }
            }
        }
```
就可以了，但是gemini不会说中文，如果你强制用中文他会说外星语。所以才选择用文字，因为如果用英语告诉你问题，很多人也不一定听的懂

**Comment by Leoskiex** [comment]
剛剛試過了,跑不動, 不知道是我問題還什麼? 出來英文練習以後直接沒有動靜:)

**Comment by nishuzumi** [comment]
> 剛剛試過了,跑不動, 不知道是我問題還什麼? 出來英文練習以後直接沒有動靜:)

想起来实际上好像还要修改执行方式，要加上语音播放才行

**Comment by blackCY** [comment]
可以运行这个文件和 gemini 对话：https://github.com/google-gemini/cookbook/blob/main/gemini-2/live_api_starter.py
但是只能对话，我还在找能把我和模型的对话输出到终端的办法

**Comment by nishuzumi** [comment]
> 可以运行这个文件和 gemini 对话：https://github.com/google-gemini/cookbook/blob/main/gemini-2/live_api_starter.py 但是只能对话，我还在找能把我和模型的对话输出到终端的办法

欢迎pr，之前也想过这个 但是这个不支持中文是比较大的遗憾，可能只能用其他方案替代

**Comment by Leoskiex** [comment]
對的, 我也試過,不過 MR. BOX寫的code用來分析語言還是真的厲害!! 尤其還可以支持其他語言的發音,那是一個準！　這語言分析設計真的別有洞天！！　所以才想知道怎麼唸，　那樣的話可能就遇到新單字可以直接練習聽和說！

**Comment by nishuzumi** [comment]
朋友们，现在加了一个新的功能，基于elevenlabs的语音播放功能，可以尝试一下
如果很长时间没有声音应该是开了代理被检测了，可以设定api.elevenlabs.io 这个域名不走代理（国内可以直连 有点慢）。
或者直接购买他们5美元一个月的套餐。
