### ISSUE TITLE
出现错误Errno -9981

### ISSUE THREAD

**Issue by amoydx** [nishuzumi/gemini-teacher#10]
<img width="656" alt="SCR-20241220-cwlt" src="https://github.com/user-attachments/assets/f636a04a-8529-4b71-ac79-1a7490b2de46" />

**Comment by nishuzumi** [comment]
是稳定复现吗？有没有复现流程？

**Comment by amoydx** [comment]
没有，我直接退出重启啦

**Comment by nishuzumi** [comment]
就好了？
