### ISSUE TITLE
大佬，我这个是为什么啊，拜托你了！

### ISSUE THREAD

**Issue by Gengar-Asuka** [nishuzumi/gemini-teacher#11]
![报错](https://github.com/user-attachments/assets/59b8e75e-a560-4312-a79c-64fdc96bb397)

**Comment by nishuzumi** [comment]
这个是网络问题，尝试修复中

**Comment by nishuzumi** [comment]
已在https://github.com/nishuzumi/gemini-teacher/commit/9bcdcc7e7d456a0a20e418e7f9dad544a3bf32fa 更新代理设置
