### ISSUE TITLE
大佬，请问这个是梯子问题吗？

### ISSUE THREAD

**Issue by chengzijiazu** [nishuzumi/gemini-teacher#12]
大佬，按照说明，配置好你的项目，但出现无法运行，请问是什么原因呢。
![image](https://github.com/user-attachments/assets/35a64906-9d65-47ac-9bab-4ab4ba9da8b4)

**Comment by nishuzumi** [comment]
是网络问题，目前在尝试修复中

**Comment by 277542952** [comment]
我的问题应该是一样的。
![74fe3e5f-3c7d-4ad6-9e7e-8201b4906a24](https://github.com/user-attachments/assets/65bccdbf-bf26-4d25-b2de-9a1e5e89056b)

**Comment by longwutu** [comment]
请问，问题已经解决了吗？

**Comment by nishuzumi** [comment]
已在https://github.com/nishuzumi/gemini-teacher/commit/9bcdcc7e7d456a0a20e418e7f9dad544a3bf32fa 更新代理设置
