### ISSUE TITLE
更新完最新的包，继续报错！

### ISSUE THREAD

**Issue by 277542952** [nishuzumi/gemini-teacher#18]
更新完最新的包，直接就报错了。
![222ddcf3-5907-4ea0-8cd8-69632a3f3f5e](https://github.com/user-attachments/assets/5e6efbce-4e15-44a7-9b3f-85070d9d43f1)

**Comment by zhangnanchao** [comment]
一样的问题

**Comment by nishuzumi** [comment]
更新后的版本必须要设定HTTP_PROXY才能使用，我修改一下改成可以选可不选吧

**Comment by nishuzumi** [comment]
已修复 https://github.com/nishuzumi/gemini-teacher/commit/72b1ca37bcc9326070594bcf058412929de0b319
