### ISSUE TITLE
小白请教一下：最后一步运行出错asyncio.exceptions.TimeoutError: timed out during handshake是怎么回事？

### ISSUE THREAD

**Issue by harveyyhh** [nishuzumi/gemini-teacher#4]

**Comment by nishuzumi** [comment]
timeout一般都是网络问题，你的梯子客户端有增强或者tun模式都需要开启

**Comment by patrenqi** [comment]
如果使用clash还需要在系统里设置好代理

**Comment by nishuzumi** [comment]
用clash就把tun模式打开就行

**Comment by torans** [comment]
同样的问题，clash 的 tun 模式已打开，环境变量也有设置。还是 timeout

**Comment by nishuzumi** [comment]
> 同样的问题，clash 的 tun 模式已打开，环境变量也有设置。还是 timeout

有可能是规则里面并没有解析到谷歌的网址

**Comment by harveyyhh** [comment]
> timeout一般都是网络问题，你的梯子客户端有增强或者tun模式都需要开启

谢谢，当时TUN模式已打开，但还是发生这个问题，而且我用api测试最基本的文本对话是没有问题的。最后我让Cline插件自动修改了N遍（其中一次是更新了`websockets` library），终于能跑了，但也是偶尔可以，大部分情况还是那个错误。让我不禁怀疑是api自身不够稳定？因为Cline插件里我也是使用的openrouter提供的gemini-2.0-flash-exp的api，修改代码过程中也是经常中断服务。

**Comment by cn-knight** [comment]
真搞不懂，啥破玩意，各种巴拉巴拉的timeout服务器连接失败。我这么稳定的VPN都搞不定，国内根本没法玩

**Comment by nishuzumi** [comment]
推荐软路由或者clash的tun模式，开全局代理，或者surge的增强模式，网络问题这个目前我还在找解决办法

**Comment by baiwfg2** [comment]
> 推荐软路由或者clash的tun模式，开全局代理，或者surge的增强模式，网络问题这个目前我还在找解决办法

不科学啊，一般在命令行设置一下环境变量http_proxy就行，要么就在代码层面用某种proxy的写法来支持配置，比如curl, wget命令都支持配置proxy。python应用应该也类似吧

**Comment by nishuzumi** [comment]
> > 推荐软路由或者clash的tun模式，开全局代理，或者surge的增强模式，网络问题这个目前我还在找解决办法
> 
> 不科学啊，一般在命令行设置一下环境变量http_proxy就行，要么就在代码层面用某种proxy的写法来支持配置，比如curl, wget命令都支持配置proxy。python应用应该也类似吧

目前来说没有支持，因为代码里面用了一个谷歌官方仓库，我看看能不能传入http proxy作为代理

**Comment by nishuzumi** [comment]
已在https://github.com/nishuzumi/gemini-teacher/commit/9bcdcc7e7d456a0a20e418e7f9dad544a3bf32fa 更新代理设置
