### ISSUE TITLE
小白求问，mac终端pip步骤报错

### ISSUE THREAD

**Issue by bigbitj** [nishuzumi/gemini-teacher#5]
我在终端前面运行的命令都是可以用的
git clone https://github.com/nishuzumi/gemini-teacher.git
cd gemini_teacher 
python3 -m venv .venv
source .venv/bin/activate
brew install portaudio
然后执行pip3 install -r requirements.txt出现的错误，
<img width="737" alt="image" src="https://github.com/user-attachments/assets/ffde8f04-2b4a-43ff-811d-99d8ea6305ab" />

 问了gpt说更新证书什么的也没什么用，python版本3.12

**Comment by kukuyuer** [comment]
用miniconda  环境试试

**Comment by nishuzumi** [comment]
感觉是按照依赖的时候就有网络问题了

**Comment by ElvisWai** [comment]
使用国内镜像试试
pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
