### ISSUE TITLE
在WIN10的cmd下运行，出现没有pyaudio模块的提示

### ISSUE THREAD

**Issue by lorsso** [nishuzumi/gemini-teacher#8]
Traceback (most recent call last):
  File "D:\gemini-teacher\starter.py", line 22, in <module>
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

**Comment by bioman82** [comment]
I guess you did not run: pip install -r requirements.txt
if you run it successfully, you should have pyaudio installed.

**Comment by lorsso** [comment]
非常感谢！的确是没运行pip install -r requirements.txt。不过，运行之后，又出现新问题：Traceback (most recent call last):
  File "D:\gemini-teacher\starter.py", line 30, in <module>
    import taskgroup, exceptiongroup
ModuleNotFoundError: No module named 'taskgroup'

**Comment by nishuzumi** [comment]
> 非常感谢！的确是没运行pip install -r requirements.txt。不过，运行之后，又出现新问题：Traceback (most recent call last): File "D:\gemini-teacher\starter.py", line 30, in import taskgroup, exceptiongroup ModuleNotFoundError: No module named 'taskgroup'

切换到3.11以上的版本
