### ISSUE TITLE
小白请教下Error: [Errno -9999] Unanticipated host error这个问题

### ISSUE THREAD

**Issue by Caijizhi** [nishuzumi/gemini-teacher#9]
Error: [Errno -9999] Unanticipated host error
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<AudioLoop.run() done, defined at D:\AI_Code\GeminiTeacher\gemini-teacher\starter.py:216> exception=ExceptionGroup('unhandled errors in a TaskGroup', [OSError(-9999, 'Unanticipated host error')])>

**Comment by nishuzumi** [comment]
应该是没有检测到麦克风？重启一下试试
